# SPDX-FileCopyrightText: 2025 Will Reed <wreed@disroot.org>
#
# SPDX-License-Identifier: GFDL-1.3-or-later

version = 1
SPDX-PackageName = "god"
SPDX-PackageSupplier = "2025 Will Reed <wreed@disroot.org>"

[[annotations]]
path = "spec/theme/admonish.css"
SPDX-FileCopyrightText = "2022 Tom Milligan"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = "art/*"
SPDX-FileCopyrightText = "2025 Will Reed <wreed@disroot.org>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "spec/theme/favicon.png"
SPDX-FileCopyrightText = "2025 Will Reed <wreed@disroot.org>"
SPDX-License-Identifier = "CC-BY-4.0"

[[annotations]]
path = "spec/**.md"
SPDX-FileCopyrightText = "2025 Will Reed <wreed@disroot.org>"
SPDX-License-Identifier = "GFDL-1.3-or-later"

[[annotations]]
path = "example/*"
SPDX-FileCopyrightText = "2025 Will Reed <wreed@disroot.org>"
SPDX-License-Identifier = "GFDL-1.3-or-later"
