# SPDX-FileCopyrightText: 2025 2025 Will Reed <wreed@disroot.org>
#
# SPDX-License-Identifier: GFDL-1.3-or-later

[book]
authors = ["Will Reed"]
language = "en"
src = "source"
title = "God Specification"

[preprocessor]
[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.1.0"

[output]
[output.html]
site-url = "/god/"
additional-css = [
    "theme/admonish.css",
    "theme/custom.css"
]
